name: SimplePerms
version: ${project.version}
main: de.***REMOVED***.simpleperms.Main
api-version: 1.16
authors: [ ***REMOVED*** ]
description: A simple Plugin to manage Permissions
website: github.***REMOVED***.me

commands:
  spadd:
  spremove:
  sptemp:
  spget: