name: SimplePerms
version: ${project.version}
main: de.marylieh.simpleperms.Main
api-version: 1.16
authors: [ Marie ]
description: A simple Plugin to manage Permissions
website: github.marylieh.me

commands:
  spadd:
  spremove:
  sptemp:
  spget:
  spgadd:
  spgpadd:
  spgprem:
  spgdel:
  spglist:
  spgplist:
  spgpladd:
  spgplrem:
  spgplget:
  spgpllist: